---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    product_slug: platform-automation
    api_token: ((pivnet-refresh-token))

- name: config
  type: git
  source:
    uri: ((pipeline-repo))
    #private_key: ((plat-auto-pipes-deploy-key.private_key))
    branch: master

jobs:
- name: install-ops-manager
  serial: true
  plan:
    - get: platform-automation-image
      resource: platform-automation
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        globs: ["*tasks*.zip"]
        unpack: true

    - get: config
    - task: var-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/test-interpolate.yml
      params:
        SKIP_MISSING: true
        VARS_FILES:
        CONFIG_FILE:
      inputs:
        - name: config
        - name: vars

    - task: download-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: gcp/download-ops-manager.yml
    
    - task: create-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/create-vm.yml
      params:
        OPSMAN_CONFIG_FILE: gcp/opsman.yml
        STATE_FILE: gcp/state.yml